export {HAPLO_DATA_ADG} from "./haplo_data_ADG";
export {SNP_DATA_ADG_1} from "./snp_data_ADG_1";

export const STRAIN_MAP_ADG = {
  "129P1/ReJ": {"color": "#b37441", "url": "/standard-designation/129P1%5CfReJ.html"},
  "129P3/J": {"color": "#00eaff", "url": "/standard-designation/129P3%5CfJ.html"},
  "129S1/SvImJ": {"color": "#ff8888", "url": "/standard-designation/129S1%5CfSvImJ.html"},
  "129S4/SvJaeJ": {"color": "#46afd2", "url": "/standard-designation/129S4%5CfSvJaeJ.html"},
  "129S5/SvEvBrd": {"color": "#d000ff", "url": "/standard-designation/129S5%5CfSvEvBrd.html"},
  "129S6/SvEvTac": {"color": "#2b53de", "url": "/standard-designation/129S6%5CfSvEvTac.html"},
  "129S7": {"color": "#b56821", "url": "/standard-designation/129S7.html"},
  "129X1/SvJ": {"color": "#ff7445", "url": "/standard-designation/129X1%5CfSvJ.html"},
  "A/J": {"color": "#ffff00", "url": "/standard-designation/A%5CfJ.html"},
  "AKR/J": {"color": "#ffb987", "url": "/standard-designation/AKR%5CfJ.html"},
  "ALR/LtJ": {"color": "#25c4cc", "url": "/standard-designation/ALR%5CfLtJ.html"},
  "B10.S-Laure": {"color": "#12c3e6", "url": "/standard-designation/B10.S-Laure.html"},
  "BALB/cByJ": {"color": "#35abbd", "url": "/standard-designation/BALB%5CfcByJ.html"},
  "BALB/cJ": {"color": "#2d12e0", "url": "/standard-designation/BALB%5CfcJ.html"},
  "C3H/HeJ": {"color": "#baaf0f", "url": "/standard-designation/C3H%5CfHeJ.html"},
  "C3H/HeNTac": {"color": "#409fa1", "url": "/standard-designation/C3H%5CfHeNTac.html"},
  "C57BL/10J": {"color": "#782a73", "url": "/standard-designation/C57BL%5Cf10J.html"},
  "C57BL/6J": {"color": "#888888", "url": "/standard-designation/C57BL%5Cf6J.html"},
"C57BL/6NJ": {"color": "#6a6e74", "url": "/standard-designation/C57BL%5Cf6NJ.html"},
"C57BLKS/J": {"color": "#a4c4e7", "url": "/standard-designation/C57BLKS%5CfJ.html"},
"C57BR/cdJ": {"color": "#c93c91", "url": "/standard-designation/C57BR%5CfcdJ.html"},
"CAST/EiJ": {"color": "#00aa00", "url": "/standard-designation/CAST%5CfEiJ.html"},
"CZECHII/EiJ": {"color": "#3494ed", "url": "/standard-designation/CZECHII%5CfEiJ.html"},
"DBA/1J": {"color": "#86c226", "url": "/standard-designation/DBA%5Cf1J.html"},
"DBA/1LacJ": {"color": "#41cfd1", "url": "/standard-designation/DBA%5Cf1LacJ.html"},
"DBA/2J": {"color": "#09db8a", "url": "/standard-designation/DBA%5Cf2J.html"},
"FVB/NJ": {"color": "#f7bcf7", "url": "/standard-designation/FVB%5CfNJ.html"},
"KK female": {"color": "#694e17", "url": "/standard-designation/KK%20female.html"},
"KK male": {"color": "#a38244", "url": "/standard-designation/KK%20male.html"},
"LEWES/EiJ": {"color": "#e69020", "url": "/standard-designation/LEWES%5CfEiJ.html"},
"LG/J": {"color": "#969be6", "url": "/standard-designation/LG%5CfJ.html"},
"LP/J": {"color": "#ebe888", "url": "/standard-designation/LP%5CfJ.html"},
"LT/SvEiJ": {"color": "#0c7022", "url": "/standard-designation/LT%5CfSvEiJ.html"},
"MSM/Ms": {"color": "#c45252", "url": "/standard-designation/MSM%5CfMs.html"},
"NOD/ShiLtJ": {"color": "#1111ff", "url": "/standard-designation/NOD%5CfShiLtJ.html"},
"NON/ShiLtJ": {"color": "#6e4612", "url": "/standard-designation/NON%5CfShiLtJ.html"},
"NOR/LtJ": {"color": "#dd98e6", "url": "/standard-designation/NOR%5CfLtJ.html"},
"NZB/BlNJ": {"color": "#9f6aa1", "url": "/standard-designation/NZB%5CfBlNJ.html"},
"NZM2410/J": {"color": "#2b53de", "url": "/standard-designation/NZM2410%5CfJ.html"},
"NZO/HlLtJ": {"color": "#00ccff", "url": "/standard-designation/NZO%5CfHlLtJ.html"},
"PANCEVO/EiJ": {"color": "#eb1aa5", "url": "/standard-designation/PANCEVO%5CfEiJ.html"},
"PERA/EiJ": {"color": "#3cba37", "url": "/standard-designation/PERA%5CfEiJ.html"},
"PWK/PhJ": {"color": "#ff0000", "url": "/standard-designation/PWK%5CfPhJ.html"},
"SJL/J": {"color": "#342c7e", "url": "/standard-designation/SJL%5CfJ.html"},
"SJL/J Mahaffey": {"color": "#cae8b2", "url": "/standard-designation/SJL%5CfJ%20Mahaffey.html"},
"SJL/Laure": {"color": "#41eb23", "url": "/standard-designation/SJL%5CfLaure.html"},
"SPRET/EiJ": {"color": "#4d6b22", "url": "/standard-designation/SPRET%5CfEiJ.html"},
"WSB/EiJ": {"color": "#9900ee", "url": "/standard-designation/WSB%5CfEiJ.html"},
"ZALENDE/EiJ": {"color": "#198ccf", "url": "/standard-designation/ZALENDE%5CfEiJ.html"}};
const SAMPLE_ID_ADG = "ADG";
const STRAIN_ID_ADG = "26972"

export const SAMPLE_ADG = {"_id": "5f56293b183b6a06dabbe5e2", "color": "#000000", "contributing_strains": ["129S1/SvImJ", "A/J", "C57BL/6J", "CAST/EiJ", "NOD/ShiLtJ", "NZO/HlLtJ", "PWK/PhJ", "WSB/EiJ"], "haplotype_candidate": false, "heterozygous_count": 1123, "heterozygous_percent": 0.7838949036360717, "homozygous_count": 136257, "homozygous_percent": 95.11234896236886, "is_public": true, "last_haplotyping": "04/01/2021 13:58 PM EST", "last_update": "04/01/2021 14:34 PM EST", "neg_ctrl_eng_tgts": [], "no_read_count": 5879, "no_read_percent": 4.103756133995072, "notes": null, "other_ids": ["1"], "owner": "tim.stearns@jax.org", "platform_id": "GigaMUGA", "pos_ctrl_eng_tgts": [], "properties": {"Index": "1", "Name": "1", "Plate": "273578", "SentrixPosition": "204680180004_R12C01", "Well": "A12"}, "sample_id": "ADG", "sex": "male", "standard_designation": "CC029", "strain_id": "26972", "tags": ["Jackson_Lab_Ciciotte_MURGIGV01_20200903_FinalReport", "GigaMUGA", "CC029", "Collaborative Cross", "CollaborativeCross"], "updated_by": "Anna.Lamoureux@jax.org", "user_can_write": false, "user_is_owner": false, "viterbi_haplotypes": {"chromosome_data": {}, "concordant_count": 0, "concordant_percent": null, "informative_count": 0}, "write_groups": []};
